version: "3"
services:
  postgresql:
    image: postgres:11.7
    ports:
      - "5442:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aqoursql_dev
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: aqoursql
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"

  postgresql-test:
    image: postgres:11.7
    ports:
      - "5443:5432"
    volumes:
      - postgresql-test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aqoursql_dev
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: aqoursql_test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"

volumes:
  postgresql-data:
    driver: local
  postgresql-test-data:
    driver: local
